import { Schema, type Model } from "mongoose";

import { baseSchemaOptions, registeredModel } from "@/models/schema-options";
import { TASK_PRIORITIES, TASK_STATUSES, type TaskPriority, type TaskStatus } from "@/types/domain";

/**
 * Independently trackable unit of work generated from a solution plan.
 *
 * Tasks are always reached through their issue (which carries the workspace),
 * so no workspaceId is denormalised here.
 */
export interface TaskDocument {
  issueId: Schema.Types.ObjectId;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  /** Position inside the task board; unique per issue by convention. */
  order: number;
  estimatedMinutes: number | null;
  assignedTo: Schema.Types.ObjectId | null;
  completedAt: Date | null;
  /** True for tasks generated by AI, false when added manually. */
  generatedByAi: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const taskSchema = new Schema<TaskDocument>(
  {
    issueId: { type: Schema.Types.ObjectId, ref: "Issue", required: true },
    title: { type: String, required: true, trim: true, minlength: 2, maxlength: 200 },
    description: { type: String, default: "", trim: true, maxlength: 4000 },
    status: { type: String, enum: [...TASK_STATUSES], default: "todo", required: true },
    priority: { type: String, enum: [...TASK_PRIORITIES], default: "medium", required: true },
    order: { type: Number, default: 0, min: 0 },
    estimatedMinutes: { type: Number, default: null, min: 0, max: 100_000 },
    assignedTo: { type: Schema.Types.ObjectId, ref: "User", default: null },
    completedAt: { type: Date, default: null },
    generatedByAi: { type: Boolean, default: false, required: true },
  },
  baseSchemaOptions,
);

taskSchema.index({ issueId: 1, order: 1 }, { name: "issue_order" });
taskSchema.index({ status: 1 }, { name: "status" });
taskSchema.index({ assignedTo: 1, status: 1 }, { name: "assignee_status" });
taskSchema.index({ issueId: 1, status: 1 }, { name: "issue_status" });
taskSchema.index(
  { title: "text", description: "text" },
  { name: "task_search", weights: { title: 5, description: 1 }, default_language: "english" },
);

export const Task: Model<TaskDocument> = registeredModel<TaskDocument>("Task", taskSchema, "tasks");
